sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - "4.1"
before_install:
  - "echo 'Installing dependencies ...'"
install:
  - npm install -g gulp@3.9.x babel-eslint@4.1.x babel-preset-es2015@6.3.x
  - npm install
branches:
  only:
    - develop
    - /^release\/.*$/
before_script:
  - "echo 'Done!'"
  - "echo 'Starting build ...'"
  - npm prune
script:
  - gulp build
after_success:
  - "echo 'Done!'"
  - "echo 'Comitting changes to repository ...'"
  - git config --global user.name "Dominique Müller"
  - git config --global user.email "dominique.m.mueller@gmail.com"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add --all && git commit -m "Automatic Travis CI build" && git push
  - "echo 'Done!'"
before_deploy:
  - "echo 'Starting deploy ...'"
deploy:
  provider: npm
  email: dominique.m.mueller@gmail.com
  api_key: NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: dominique-mueller/burgerlicious
after_deploy:
  - "echo 'Done!'"
