# General settings
dist: trusty
sudo: false
language: node_js
node_js:
  "node"
cache: false
notifications:
  email: false
branches:
  only:
    - master
    - develop

# Build stages
stages:
  - name: build
  - name: release
    if: branch = master

# Build jobs
jobs:
  include:

    - stage: build
      install:
        - npm ci
      script:
        - npm run build

    - stage: release
      install:
        - npm ci
      script:
        - npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: dominique.m.mueller@gmail.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
      after_deploy:
        - cd ..
